spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: springboot
  profiles:
    active: dev
  freemarker:
#    template-loader-path: ["classpath:/templates/"]
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    check-template-location: true
    template-loader-path: classpath:/templates
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    settings:
     default_encoding: UTF-8
     output_encoding: UTF-8
     url_escaping_charset: UTF-8
     tag_syntax: auto_detect
     locale: zh_CN
     datetime_format: yyyy-MM-dd HH:mm:ss
     date_format: yyyy-MM-dd
     time_format: HH:mm:ss

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml


