spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-classs-name: com.mysql.jdbc.Driver
server:
  port: 8081



